"""Tables created

Revision ID: 75b6299d398d
Revises:
Create Date: 2025-06-08 21:50:56.686034

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75b6299d398d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("tournaments", sa.Column("id", sa.Integer(), nullable=False), sa.Column("name", sa.String(length=255), nullable=False), sa.Column("max_players", sa.Integer(), nullable=False), sa.CheckConstraint("max_players >= 1", name="check_max_players_positive"), sa.PrimaryKeyConstraint("id"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tournaments")
    # ### end Alembic commands ###
