"""start_at column added

Revision ID: 7fc50b7409ca
Revises: 75b6299d398d
Create Date: 2025-06-08 21:54:28.700058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fc50b7409ca'
down_revision: Union[str, None] = '75b6299d398d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('start_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'start_at')
    # ### end Alembic commands ###
