"""Registration qo'shildi

Revision ID: fb21f7834bb5
Revises: f9836ca18258
Create Date: 2025-06-09 23:15:07.072908

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fb21f7834bb5'
down_revision: str | None = 'f9836ca18258'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('registered_at', sa.DateTime(), nullable=True))
    op.drop_column('registrations', 'registration_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('registration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('registrations', 'registered_at')
    # ### end Alembic commands ###
